### ISSUE TITLE
lein repl :connect localhost:1112 doesn't work

### ISSUE THREAD

**Issue by rogergl** [matlux/jvm-breakglass#19]
Hi,

the server throws the following exception:

ERROR: Unhandled REPL handler exception processing message {:id 7e129e42-acf2-4d05-bc27-beedcf66334b, :op clone}
java.lang.NoClassDefFoundError: clojure/tools/nrepl/StdOutBuffer
	at clojure.tools.nrepl.middleware.session$session_out.invoke(session.clj:26)
	at clojure.tools.nrepl.middleware.session$create_session.invoke(session.clj:118)
	at clojure.tools.nrepl.middleware.session$create_session.invoke(session.clj:114)
	at clojure.tools.nrepl.middleware.session$session$fn__657.invoke(session.clj:178)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__393.invoke(middleware.clj:17)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:18)
	at clojure.tools.nrepl.server$handle$fn__704.invoke(server.clj:27)
	at clojure.core$binding_conveyor_fn$fn__4145.invoke(core.clj:1910)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

**Comment by matlux** [comment]
I assume you're following the ["quick demonstration of this project"](https://github.com/matlux/jvm-breakglass/blob/master/README.md#quick-demonstration-of-this-project) on the Readme.md available under:
https://github.com/matlux/jvm-breakglass/blob/master/README.md#quick-demonstration-of-this-project

I can't see anything obvious when I reproduce the steps on my side with my Mac OS X 10.9.5. We'll have to figure out what was different on your side to get to the bottom of it.

I have reproduced and reviewed every steps. I have just removed some ambiguities I could see in the tutorial. So maybe try again and tell me:

Do you see the following message after you've started the demonstration server? 
"Retrieve Employees from NY or London:
Retrieve Employees from NY or London:
..."

If you don't then it could be a classpath issue. I forgot to mention that the startSpringServer.sh do assume that your maven repository is ~/.m2/repository (which is the Maven default). Make sure you adapt the script to the relevant maven setup you have.

Once the server output is correct, don't interrupt the process. Then can you make sure you open a second window and stay outside of any project directory before you type `lein repl :connect localhost:1112` ?

Can you give me a precise list of steps you have followed and a copy of their output?

What is your OS version?

What version of Java and Lein are you using?
For example type:
$ lein version
Leiningen 2.3.4 on Java 1.7.0_40 Java HotSpot(TM) 64-Bit Server VM

**Comment by matlux** [comment]
Hang on I have managed to reproduce the issue. Give me a bit more time to work it out.

**Comment by matlux** [comment]
Should be fixed. Please test and let me know.

**Comment by rogergl** [comment]
Great. It is working now.

**Comment by matlux** [comment]
Cool. Thanks for reporting it.
